name: Run pytest
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Pythonの環境をセットアップ
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      #
      - name: Build Docker image  # ステップの名前
        run: docker build -t my_image .
                   
      # PyTest -> JUnit XML形式で結果を出力
      #ボリュームを介してDockerコンテナ内でのテスト結果を現在のディレクトリへ反映させる
      - name: PyTest
        run: docker run -v "$(pwd)":/workspace my_image python -m pytest test --junitxml=/workspace/results/pytest.xml
        continue-on-error: true
      #ファイルをダウンロード
      - name: Download file
        run: |
          curl -H "Authorization: token ${{ secrets.USER_TOKEN }}" -o pretrained_model.txt https://github.com/koma757/actions-test/main/pretrained_model
        
      # 現在のディレクトリを表示
      - name: Display current directory
        run: ls
        
      
